//import com.example.drool.PolicyMakingDroolExample.model.PasswordPolicy;
import com.example.drool.PolicyMakingDroolExample.model.PasswordPolicyRules;
import com.example.drool.PolicyMakingDroolExample.model.Request;
//import com.example.drool.PolicyMakingDroolExample.model.AllowCapitalAndSpecialCharacters;
//import com.example.drool.PolicyMakingDroolExample.exceptiom.SmallPasswordException;

global java.util.List<String> globalExceptionMessages;

dialect "mvel"

rule "Check Minimum Password Length"
when
   $rules: PasswordPolicyRules($minLength: minPasswordLength)
   $requestPassword: Request($password : password)
   eval($password.length() < $minLength)
then
    
    System.out.println("Password does not meet the minimum length requirement");
    globalExceptionMessages.add("Password does not meet the minimum length requirement");
end


//***********************************************************************************************************

rule "Check Maximum Password Length"
when
   $rules: PasswordPolicyRules($maxLength: maxPasswordLength)
   $requestPassword: Request($password : password)
    eval($password.length() > $maxLength)
then
   
    System.out.println("Password does not meet the maximum length requirement");
    globalExceptionMessages.add("Password does not meet the maximum length requirement");
    
end


//***************************************************************************************************************

rule "Check Minimum Digits"
when
    $rules: PasswordPolicyRules(minDigits != null, minDigits > 0, $minDigits: minDigits)
    $requestPassword: Request($password : password)
    eval($password.replaceAll("[^0-9]", "").length() < $rules.minDigits)
then
    System.out.println("Password does not meet the minimum digits requirement");
     globalExceptionMessages.add("Password does not meet the minimum digits requirement");
end

//******************************************************************************************************************

rule "Check Minimum Special Characters"
when
  // $requestPassword: Request($password : password)
   $requestPassword: Request($password : password)
   $rules : PasswordPolicyRules(
        allowCapitalAndSpecialCharacters != null,
        allowCapitalAndSpecialCharacters.minSpecialCharacters != null,
        allowCapitalAndSpecialCharacters.minSpecialCharacters > 0,
        $minSpecialCharacters: allowCapitalAndSpecialCharacters.minSpecialCharacters)
        eval($password.replaceAll("[^\\p{Punct}]", "").length() <  $minSpecialCharacters)
then
    System.out.println("Password does not meet the minimum special character requirement");
    globalExceptionMessages.add("Password does not meet the minimum special character requirement");
end

//*********************************************************************************************************************
rule "Check Minimum Capital Characters"
when
    $requestPassword: Request($password : password)
    $rules: PasswordPolicyRules(
        allowCapitalAndSpecialCharacters != null,
        allowCapitalAndSpecialCharacters.minCapitalCharacters != null,
        allowCapitalAndSpecialCharacters.minCapitalCharacters > 0,
        $minCapitalCharacters: allowCapitalAndSpecialCharacters.minCapitalCharacters)
        eval($password.replaceAll("[^A-Z]", "").length() <  $minCapitalCharacters )
then
    System.out.println("Password does not meet the minimum capital character requirement");
     globalExceptionMessages.add("Password does not meet the minimum capital character requirement");
end














