import com.example.drool.PolicyMakingDroolExample.model.PasswordPolicy;
import com.example.drool.PolicyMakingDroolExample.model.PasswordPolicyRules;
import com.example.drool.PolicyMakingDroolExample.model.Request;
import com.example.drool.PolicyMakingDroolExample.model.AllowCapitalAndSpecialCharacters;
import com.example.drool.PolicyMakingDroolExample.exceptiom.SmallPasswordException;

global java.util.List<String> globalExceptionMessages;

dialect "mvel"

rule "Check Minimum Password Length"
when
   $rules: PasswordPolicyRules($minLength: minPasswordLength)
   $password : String()
   eval($password.length() < $minLength)
then
    
    System.out.println("Password does not meet the minimum length requirement");
    globalExceptionMessages.add("Password does not meet the minimum length requirement");
end


